### ISSUE TITLE
Uncaught TypeError: Cannot read property 'keyIdentifier' of undefined

### ISSUE THREAD

**Issue by despairblue** [skandasoft/navigate#6] opened 2015-05-03 22:29 UTC
Use command palette -> _Navigate: Browser_

**Atom Version**: 0.196.0
**System**: linux 3.14.39-1-lts
**Thrown From**: [navigate](https://github.com/skandasoft/navigate) package, v0.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'keyIdentifier' of undefined

```
At /home/despairblue/.atom/packages/navigate/lib/navigate.coffee:42

TypeError: Cannot read property 'keyIdentifier' of undefined
  at Object.module.exports.browserOption (/home/despairblue/.atom/packages/navigate/lib/navigate.coffee:42:28)
  at Object.module.exports.openBrowser (/home/despairblue/.atom/packages/navigate/lib/navigate.coffee:55:6)
  at atom-text-editor.module.exports.activate.atom.commands.add.navigate:browser (/home/despairblue/.atom/packages/navigate/lib/navigate.coffee:39:38)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.module.exports.SelectListView.initialize.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
     -1:27.7.0 core:cancel (atom-text-editor.editor)
     -1:18.3.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:18.3.0 core:cancel (atom-text-editor.editor.mini)
  5x -1:06.9.0 core:move-down (atom-text-editor.editor.mini)
     -1:06.1.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:06.1.0 core:cancel (atom-text-editor.editor.mini)
  2x -0:37.3.0 tree-view:toggle (atom-text-editor.editor)
     -0:35.9.0 tree-view:reveal-active-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -0:09.8.0 core:move-up (atom-text-editor.editor)
     -0:08.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor)
  2x -0:08.2.0 core:move-up (atom-text-editor.editor)
  2x -0:07.7.0 core:move-left (atom-text-editor.editor)
     -0:06.5.0 command-palette:toggle (atom-text-editor.editor)
     -0:05.1.0 core:backspace (atom-text-editor.editor.mini)
     -0:03.5.0 core:confirm (atom-text-editor.editor.mini)
     -0:03.5.0 navigate:browser (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "themed-settings",
      "linter-scspell",
      "filetype-color",
      "atom-pair",
      "linter-eslint",
      "es-navigation",
      "autocomplete",
      "tab-smart-sort",
      "starred-package-installer",
      "zentabs",
      "linter-jshint",
      "block-cursor",
      "test-status",
      "minimap",
      "minimap-color-highlight",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "travis-ci-status",
      "pane-layout-plus",
      "symbols-tree-view",
      "package-cop"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "navigate": {
    "dblclick": true
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.1.0
atom-alignment, v0.12.0
atom-color-highlight, v3.0.9
atom-ternjs, v0.5.23
atom-zeal, v0.1.0
autocomplete-css, v0.6.0
autocomplete-emojis, v2.2.0
autocomplete-html, v0.6.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.1
autocomplete-snippets, v1.3.0
block-travel, v1.0.2
bug-report, v0.6.3
color-picker, v1.7.0
compare-files, v0.4.1
docblockr, v0.6.3
editorconfig, v1.0.0
file-icons, v1.5.4
git-log, v0.3.0
go-plus, v3.3.9
grammar-token-limit, v0.1.1
highlight-selected, v0.9.2
indentation-indicator, v0.5.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.9
language-dockerfile, v0.1.0
language-dot, v1.6.0
language-fish-shell, v1.0.2
language-haskell, v1.0.0
language-javascript-better, v1.5.0
language-latex, v0.6.1
language-nimrod, v0.1.0
language-puppet, v0.11.0
language-tss, v0.1.0
latex, v0.22.0
linter, v0.12.1
linter-coffeelint, v0.2.2
linter-htmlhint, v0.0.13
linter-js-standard, v0.1.5
linter-js-yaml, v1.0.0
linter-puppet-lint, v0.2.8
linter-shellcheck, v0.0.7
markdown-scroll-sync, v0.3.3
navigate, v0.1.0
open-last-project, v0.4.1
pdf-view, v0.22.0
project-manager, v1.15.5
regex-railroad-diagram, v0.7.4
tabs-to-spaces, v0.10.0

# Dev
No dev packages
```

**Comment by skandasoft** [comment] 2015-05-03 22:58
The problem is I don't have linux and looks the event generated from the key stroke evt.originalEvent.keyIdentifier is not available..somebody would need to debug at linux to fix this..I will add the tag for help

**Comment by skandasoft** [comment] 2015-05-04 01:01
I would suggest to use the keyboard custom keys --> maintained in the config in the package..you can customize..and I think the double click might be choosing just the word so use the f2 key

**Comment by skandasoft** [comment] 2015-05-09 15:16
The default navigation when you go through the browser-plus:navigate would be ctrl-f1 --> which is currently set as google..so it should throw any error any more..check it out. closing the issue..please reopen if it still exists.

**Closed as completed by skandasoft** 2015-05-09 15:16 UTC
Labels: help wanted
